services:
  postgres:
    image: postgres
    container_name: threads-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: threads
      POSTGRES_PASSWORD: threads
    dns:
      - 8.8.8.8
      - 1.1.1.1
volumes:
  postgres_data:
